name: "Release using semantic release"
on:
  workflow_call:
    secrets:
      GITHUB_NPM_TOKEN:
        description: The Github token that is allowed to install & publish Github NPM packages
        required: true
    inputs:
      artifact-name:
        description: Name of the build artifacts
        type: string
        required: false
        default: build-artifacts
      artifact-path:
        description: Path to extract the build artifacts
        type: string
        required: false
        default: .dist
      release-branches:
        description: List of branches on which to publish (JSON-stringified)
        type: string
        required: false
        default: '["refs/heads/next", "refs/heads/main"]'

jobs:
  publish:
    name: ${{ contains(fromJSON(inputs.release-branches), github.ref) && 'publish' || 'dry run' }}
    environment: ${{ github.ref == 'refs/heads/main' && 'publish' || contains(fromJSON(inputs.release-branches), github.ref) && 'beta' || 'dry run' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-node
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
      - run: ${{ contains(fromJSON(inputs.release-branches), github.ref) && 'npx semantic-release' || 'npx semantic-release --dry-run' }}
        shell: bash
        env:
          GIT_AUTHOR_NAME: "Hoid"
          GIT_COMMITTER_NAME: "Hoid"
          GIT_AUTHOR_EMAIL: "hoid@zefiros.io"
          GIT_COMMITTER_EMAIL: "hoid@zefiros.io"
          # Needed for publishing with semantic release
          NPM_TOKEN: ${{ secrets.GITHUB_NPM_TOKEN }}
      - run: npx node-standards make-release
        if: github.ref == 'refs/heads/next'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
