name: Typescript standard pipeline for tests & checks
on:
  workflow_call:
    secrets:
      GITHUB_NPM_TOKEN:
        description: The Github token that is allowed to install Github NPM packages
        required: true
      CODECOV_TOKEN:
        description: The token to authenticate with Codecov, for publishing coverage artifacts
        required: true

    # TODO: make this dynamic
    outputs:
      build-artifact-name:
        description: Name of the build artifacts
        value: build-artifacts
      build-artifact-path:
        description: Path of the build artifacts
        value: .dist

env:
  GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_NPM_TOKEN }}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-node
        id: setup-node

  lint:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-node
      - run: npm run lint

  types:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-node
      - run: npm run check:types

  test:
    needs: setup
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-node
      - run: npm run check:coverage
      - run: npx codecov

  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-node
      - run: npm run build
      - name: Dist artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: .dist
